<?php
namespace Home\Controller;

class IndexController extends HomeController {

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->meta_title = '首页';
    }

    public function index(){
        $this->display();
    }
}